Add @ logo to pages
ADORSYS-GIS/gis-presentation pull request #2
Opened 2024-07-18 16:28 UTC by Calebasah

2024-07-18 16:45 UTC, stephane-segning requested changes
Please can you do a picture of the result?

2024-07-18 16:45 UTC, stephane-segning commented on package-lock.json
Use yarn instead and remove this file

2024-07-18 17:12 UTC, Calebasah commented
> Please can you do a picture of the result?

![Screenshot from 2024-07-18 18-10-29](https://github.com/user-attachments/assets/c565f199-09d2-4a76-8a15-7cb2fae05028)

2024-07-18 17:27 UTC, Calebasah commented on package-lock.json
Done!
Mr @stephane-segning, are the changes okay?

2024-07-18 18:45 UTC, stephane-segning requested changes

2024-07-18 18:45 UTC, stephane-segning commented on yarn.lock
Please add yarn to this file. Use the command yarn install for that

2024-07-19 07:59 UTC, stephane-segning approved these changes

2024-07-19 07:59 UTC, merged